# Generated by Django 2.2.6 on 2019-10-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='activity_type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
