# Generated by Django 2.2.6 on 2019-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191007_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='lon',
            field=models.FloatField(),
        ),
    ]
