# Generated by Django 2.2.6 on 2019-10-12 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191007_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='request_to',
        ),
        migrations.AddField(
            model_name='deal',
            name='user_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.UserActivity'),
            preserve_default=False,
        ),
    ]
