# Generated by Django 2.1.7 on 2019-09-27 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190905_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=30)),
                ('lon', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('description', models.CharField(max_length=250)),
                ('working_days', models.CharField(max_length=50)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='long',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rating',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='male', max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='security_answer',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='security_question',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeactivity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee'),
        ),
    ]
