# Generated by Django 2.1.7 on 2019-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190930_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
