# Generated by Django 2.1.7 on 2019-09-27 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190927_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeactivity',
            name='id',
        ),
        migrations.AddField(
            model_name='deal',
            name='comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='employeeactivity',
            name='employee_activity_id',
            field=models.BigAutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
