# Generated by Django 2.2.6 on 2019-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191012_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('R', 'Request'), ('C', 'Cancelled'), ('A', 'Accepted'), ('D', 'Declined'), ('F', 'Finished')], default='R', max_length=1),
        ),
    ]
