# Generated by Django 2.2.6 on 2019-10-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='quota',
            field=models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('H', 'Hour'), ('P', 'Piece'), ('V', 'Visit'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
