# Generated by Django 2.1.7 on 2019-09-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190927_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='employeeactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='employeeactivity',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='EmployeeActivity',
        ),
    ]
