# Generated by Django 2.2.6 on 2019-10-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='quota',
            field=models.CharField(blank=True, choices=[('D', 'Per Day'), ('W', 'Per Week'), ('H', 'Per Hour'), ('P', 'Per Piece'), ('V', 'Per Visit'), ('O', 'Other')], default='D', max_length=1, null=True),
        ),
    ]
